FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk-headless \
    git zip unzip wget \
    zlib1g-dev libffi-dev \
    libncurses5 libstdc++6 \
    ccache autoconf automake libtool \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH
RUN pip3 install buildozer cython==0.29.37
WORKDIR /home/user/hostcwd
CMD ["buildozer", "-v", "android", "debug"]
